"""
OA Cheating Detector -- ek simple AI agent (koi LangGraph nahi)

Ek LLM + 4 tools. LLM khud decide karta hai kaunsa check chalana hai, kitni baar.
Max 5 attempts. End mein ek report banti hai -- lekin FAISLA INSAAN karta hai.

    System flags, human decides.

Run:
    uv run agent.py longest_substring divya
    uv run agent.py longest_substring meera
"""

import argparse
import json
from datetime import datetime

from groq import BadRequestError

from ai_judge import judge
from config import MODEL, ROOT, groq, load_problem, print_tokens, track
from moss import COMMON_THRESHOLD, matches_for
from reference import reference_match
from same_bug import same_bug_for


MAX_ATTEMPTS = 5
REVIEWS_FILE = ROOT / "reviews.json"

SYSTEM_PROMPT = """
You are an assistant to the integrity team of an online coding assessment (OA).
You investigate ONE candidate's submission and prepare evidence for a HUMAN reviewer.
You never decide that someone cheated. The human decides.

Tools:
- check_classmate_similarity: MOSS-style fingerprint match against other candidates.
- check_same_bug: runs the tests; shows who produced the exact same WRONG outputs.
- check_ai_reference_match: MOSS match against solutions generated by AI models.
- check_ai_style: heuristic + LLM guess of whether the code "looks" AI-written.

How to weigh evidence:
- Strong: high classmate similarity TOGETHER with the same wrong outputs; very high match to an AI reference.
- Weak: AI style alone. Clean, well-named code is not proof of anything. Short or textbook
  problems naturally look alike.
- Only state facts that a tool returned or that you can see in the candidate's code.
  You have NOT seen any other candidate's code -- never describe what their code contains.
- Questions for the next round must quote real lines from the candidate's code.
- You have at most 5 turns, so call the independent checks together in your first turn.

Final answer format (plain text, no tool call):
RISK: LOW | MEDIUM | HIGH
EVIDENCE:
- <each point with the numbers and names>
CAVEATS:
- <why this could be innocent>
ASK IN THE NEXT ROUND:
- <1-2 questions about specific lines that a genuine author could answer easily>
"""


def tool(name: str, description: str, params: dict | None = None) -> dict:
    return {
        "type": "function",
        "function": {
            "name": name,
            "description": description,
            "parameters": {"type": "object", "properties": params or {}, "required": list(params or {})},
        },
    }


TOOLS = [
    tool("check_classmate_similarity", "MOSS similarity of this submission against every other candidate."),
    tool("check_same_bug", "Run the hidden tests; list candidates with the exact same wrong outputs."),
    tool("check_ai_reference_match", "MOSS similarity against solutions generated by GPT-OSS and Qwen."),
    tool("check_ai_style", "Heuristic + LLM-as-judge estimate of whether the code looks AI-written."),
]


def make_tools(problem: dict, student: str) -> dict:
    """Har tool ek normal Python function hai. Ye sirf is ek student ke liye kaam karte hain."""
    code = problem["submissions"][student]
    pid = problem["id"]

    return {
        "check_classmate_similarity": lambda: {
            "class_size": len(problem["submissions"]),
            "note": f"fingerprints shared by more than {COMMON_THRESHOLD} candidates are ignored as common code",
            "top_matches": matches_for(pid, student),
        },
        "check_same_bug": lambda: same_bug_for(pid, student),
        "check_ai_reference_match": lambda: reference_match(pid, student),
        "check_ai_style": lambda: judge(code, problem["statement"], problem["starter"]),
    }


def ask_llm(problem_id: str, student: str) -> str:
    problem = load_problem(problem_id)
    functions = make_tools(problem, student)

    # candidate ka code line numbers ke saath -- taaki agent asli lines quote kare, invent na kare
    code = problem["submissions"][student]
    numbered = "\n".join(f"{n:>3} {line}" for n, line in enumerate(code.splitlines(), 1))

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": (
            f"Question:\n{problem['statement']}\n\n"
            f"Candidate '{student}' submitted:\n{numbered}\n\nInvestigate this candidate."
        )},
    ]

    for attempt in range(1, MAX_ATTEMPTS + 1):
        print(f"  [agent] attempt {attempt}")

        # last attempt pe tools band -- ab jo mila usse report likho
        tools_now = TOOLS if attempt < MAX_ATTEMPTS else None
        try:
            response = groq.chat.completions.create(model=MODEL, messages=messages, tools=tools_now)
        except BadRequestError:
            # gpt-oss kabhi kabhi galat tool call invent karta hai; groq reject karta hai
            print("  [agent]   malformed tool call rejected by groq, retrying")
            continue
        track("agent", response.usage)

        message = response.choices[0].message

        # koi tool call nahi -> final report
        if not message.tool_calls:
            return message.content

        messages.append({
            "role": "assistant",
            "content": message.content or "",
            "tool_calls": [tc.model_dump() for tc in message.tool_calls],
        })

        for tool_call in message.tool_calls:
            name = tool_call.function.name
            print(f"  [agent]   -> {name}")
            if name in functions:
                result = functions[name]()
            else:
                result = f"Unknown tool {name}"
            messages.append({
                "role": "tool",
                "tool_call_id": tool_call.id,
                "content": result if isinstance(result, str) else json.dumps(result),
            })

    return "RISK: UNKNOWN\nAgent ran out of attempts. Review manually."


# ============================================================
# HUMAN IN THE LOOP
# ============================================================


def human_review(problem_id: str, student: str, report: str):
    print("\n" + "=" * 60)
    print("HUMAN REVIEW  (system flags, human decides)")
    print("=" * 60)
    try:
        choice = input("Decision -- [c]lear / [f]ollow-up interview / [e]scalate: ").strip().lower()
        note = input("Note (optional): ").strip()
    except EOFError:
        print("(no reviewer input, decision not saved)")
        return

    decision = {"c": "cleared", "f": "follow-up interview", "e": "escalated"}.get(choice[:1], "undecided")
    reviews = json.loads(REVIEWS_FILE.read_text(encoding="utf-8")) if REVIEWS_FILE.exists() else []
    reviews.append({
        "time": datetime.now().isoformat(timespec="seconds"),
        "problem": problem_id,
        "candidate": student,
        "agent_report": report,
        "decision": decision,
        "note": note,
    })
    REVIEWS_FILE.write_text(json.dumps(reviews, indent=2), encoding="utf-8")
    print(f"Saved: {student} -> {decision}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("problem")
    parser.add_argument("student")
    parser.add_argument("--no-review", action="store_true", help="human review prompt skip karo")
    args = parser.parse_args()

    print(f"\nInvestigating '{args.student}' on '{args.problem}'\n")
    report = ask_llm(args.problem, args.student)

    print("\n" + "=" * 60)
    print(f"AGENT REPORT: {args.student}")
    print("=" * 60)
    print(report)
    print_tokens()

    if not args.no_review:
        human_review(args.problem, args.student, report)
