"""
AI style check: "insaan ne likha ya AI ne?"

MOSS students ko EK-DOOSRE se compare karta hai. Ye check code ko compare karta hai
"AI ka code kaisa dikhta hai" se.

Do tareeke:
    1. heuristic_score() -- offline, free, har signal explain kar sakte hain
    2. llm_judge()        -- LLM-as-judge, structured JSON output

WARNING: AI detectors ke false positives bahut hote hain. Clean likhne wala insaan bhi
flag ho sakta hai. Ye sirf TRIAGE hai, proof nahi.

Run:
    uv run ai_judge.py longest_substring alice
    uv run ai_judge.py longest_substring eshan --llm
"""

import argparse
import ast
import json
import re

from config import MODEL, groq, load_problem, print_tokens, track


FLAG_AT = 0.6

# loop wale ek-letter naam sab use karte hain, inse kuch pata nahi chalta
NEUTRAL_NAMES = {"i", "j", "k", "n", "m", "s", "_", "x", "y", "self"}
SHORTHAND = re.compile(r"^(temp\d*|tmp\d*|ans\d*|res\d*|mx|mn|maxi|mini|cnt|flag\d*|st|sm|mp|[a-z]\d+|curr?\d+)$")


# ============================================================
# 1. HEURISTICS
# ============================================================


def defined_names(tree: ast.AST) -> set[str]:
    """Wo naam jo student ne khud banaye: variables, parameters, functions."""
    names = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Store):
            names.add(node.id)
        elif isinstance(node, ast.arg):
            names.add(node.arg)
        elif isinstance(node, ast.FunctionDef):
            names.add(node.name)
    return names


def is_descriptive(name: str) -> bool:
    # max_len, lastSeen, current_window -> descriptive
    return "_" in name.strip("_") or any(c.isupper() for c in name[1:]) or len(name) >= 6


def heuristic_score(code: str, starter: str = "") -> dict:
    """Score 0..1 (1 = bahut AI jaisa) + wo signals jinse score bana."""
    signals = []  # (weight, reason)   +ve = AI jaisa,  -ve = insaan jaisa

    try:
        tree = ast.parse(code)
    except SyntaxError:
        return {"score": 0.2, "signals": ["code parse nahi hua (AI rarely likhta hai)"], "flag": False}

    # --- naming ---
    starter_names = defined_names(ast.parse(starter)) if starter else set()
    names = defined_names(tree) - starter_names - NEUTRAL_NAMES
    if names:
        descriptive = sorted(n for n in names if is_descriptive(n))
        ratio = len(descriptive) / len(names)
        if ratio >= 0.6:
            signals.append((0.2, f"descriptive names everywhere: {', '.join(descriptive[:4])}"))
        elif ratio <= 0.3:
            short = sorted(n for n in names if not is_descriptive(n))
            signals.append((-0.15, f"short names: {', '.join(short[:4])}"))

    shorthand = sorted(n for n in names if SHORTHAND.match(n))
    if shorthand:
        signals.append((-0.15, f"shorthand/junk names: {', '.join(shorthand[:4])}"))

    # --- docstrings + type hints ---
    functions = [n for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)]
    if any(ast.get_docstring(f) for f in functions):
        signals.append((0.2, "function docstring"))
    if any(f.returns or any(a.annotation for a in f.args.args) for f in functions):
        signals.append((0.15, "type hints"))

    # --- comments ---
    comments = re.findall(r"#\s*(.*)", code)
    sentences = [c for c in comments if c[:1].isupper() and len(c.split()) >= 4]
    commented_code = [c for c in comments if re.search(r"print\(|\w+\s*=\s*\w|return\b", c)]
    if len(sentences) >= 2:
        signals.append((0.15, f"{len(sentences)} neat full-sentence comments"))
    if commented_code:
        signals.append((-0.2, f"commented-out debug code: '# {commented_code[0][:30]}'"))

    # --- structure ---
    if '__name__ == "__main__"' in code or "__name__ == '__main__'" in code:
        signals.append((0.1, "if __name__ == '__main__' guard"))
    if re.search(r"^\s+if not \w+\s*:|^\s+if len\(\w+\)\s*(==\s*0|<\s*2)", code, flags=re.M):
        signals.append((0.1, "edge cases handled up front"))

    # --- spacing: a=b aur a = b dono? insaan mix karte hain ---
    cramped = re.findall(r"^\s*\w+(=|\+=|-=)[\w\[(-]", code, flags=re.M)
    if cramped:
        signals.append((-0.1, "cramped spacing like 'l=0' / 'l+=1'"))

    score = min(1.0, max(0.0, 0.4 + sum(w for w, _ in signals)))
    return {
        "score": round(score, 2),
        "signals": [f"{'+' if w > 0 else '-'} {reason}" for w, reason in signals],
        "flag": score >= FLAG_AT,
    }


# ============================================================
# 2. LLM-AS-JUDGE (structured output)
# ============================================================

JUDGE_PROMPT = """
You help an online-assessment integrity team triage coding submissions.
Estimate how likely it is that this code was generated by an AI assistant (ChatGPT, Claude,
Gemini ...) rather than typed by a human candidate under time pressure.

Be calibrated:
- Clean, well-named code is NOT proof of AI. Many strong humans write clean code.
- Look for concrete signals: explanatory comments a human would not bother with in a timed test,
  docstrings, type hints, textbook variable names, every edge case handled up front,
  main() guards, versus shorthand names, leftover debug prints, inconsistent style.
- Your answer is only a triage hint for a human reviewer, never a verdict.
"""

JUDGE_SCHEMA = {
    "type": "object",
    "properties": {
        "ai_likelihood": {"type": "number", "description": "0 = clearly human, 1 = clearly AI"},
        "signals": {"type": "array", "items": {"type": "string"}},
        "reasoning": {"type": "string", "description": "one or two sentences"},
    },
    "required": ["ai_likelihood", "signals", "reasoning"],
    "additionalProperties": False,
}


def llm_judge(code: str, statement: str = "") -> dict:
    response = groq.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": JUDGE_PROMPT},
            {"role": "user", "content": f"Question:\n{statement}\n\nSubmission:\n```python\n{code}```"},
        ],
        response_format={
            "type": "json_schema",
            "json_schema": {"name": "ai_judgement", "strict": True, "schema": JUDGE_SCHEMA},
        },
        temperature=0,
    )
    track("ai_judge", response.usage)
    result = json.loads(response.choices[0].message.content)
    result["flag"] = result["ai_likelihood"] >= FLAG_AT
    return result


def judge(code: str, statement: str = "", starter: str = "", use_llm: bool = True) -> dict:
    result = {"heuristic": heuristic_score(code, starter)}
    if use_llm:
        result["llm"] = llm_judge(code, statement)
    return result


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("problem")
    parser.add_argument("student", nargs="?", help="khaali chhodo to poori class")
    parser.add_argument("--llm", action="store_true", help="LLM judge bhi chalao (tokens lagte hain)")
    args = parser.parse_args()

    problem = load_problem(args.problem)
    students = [args.student] if args.student else list(problem["submissions"])

    for student in students:
        r = judge(problem["submissions"][student], problem["statement"], problem["starter"], args.llm)
        h = r["heuristic"]
        print(f"\n{student}: heuristic {h['score']:.2f}{'  <-- FLAG' if h['flag'] else ''}")
        for s in h["signals"]:
            print(f"    {s}")
        if "llm" in r:
            l = r["llm"]
            print(f"  LLM judge {l['ai_likelihood']:.2f}{'  <-- FLAG' if l['flag'] else ''}: {l['reasoning']}")

    if args.llm:
        print_tokens()
